name: recurring_alarm
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  awesome_notifications: ^0.9.3
  workmanager: ^0.5.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  flutter_riverpod: ^2.5.1
  fluttertoast: ^8.2.6
  go_router: ^14.2.1
  path: ^1.9.0
  sqflite: ^2.3.3
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
